StudentPlan/Models/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace StudentPlan.Models
{
    public class Student
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int StudentId{ get; set; }

        [Required]
        [StringLength(40, MinimumLength = 3)]
        [Display(Name = "Family")]
        public string Family { get; set;}

        [Required]
        [StringLength(40, MinimumLength = 3)]
        [Display(Name = "Given")]
        public string Given{ get; set; }

        public string Snumber{get; set;}
        public int Number919{ get; set; }

        public bool Done { get; set; }

        public ICollection<DegreePlan> DegreePlans { get; set; }
        public ICollection<StudentTerm> StudentTerms { get; set; }
    }
}

StudentPlan/Controllers/DegreePlansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentPlan.Data;
using StudentPlan.Models;

namespace StudentPlan.Controllers
{
    public class DegreePlansController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DegreePlansController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DegreePlans
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["StudentidSortParm"] = sortOrder == "Studentid" ? "Studentid_desc" : "Studentid";
            ViewData["DegreePlanAbvSortParm"] = String.IsNullOrEmpty(sortOrder) ? "DegreeplanAbv_desc" : "";
            ViewData["DegreePlanNameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "DegreePlanName_desc" : "";
            ViewData["DegreeidSortParm"] = sortOrder == "Degreesid" ? "Degreeid_desc" : "Degreeid";
            ViewData["CurrentFilter"] = searchString;
            var degreeplans = from s in _context.DegreePlans
                              select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                degreeplans = degreeplans.Where(s => s.DegreePlanAbbrev.Contains(searchString)
                                       || s.DegreePlanName.Contains(searchString) || s.StudentId.ToString().Contains(searchString) || s.DegreeId.ToString().Contains(searchString));
            }
            switch (sortOrder)
            {
                case "Studentid_desc":
                    degreeplans = degreeplans.OrderByDescending(s => s.StudentId);
                    break;
                case "Studentid":
                    degreeplans = degreeplans.OrderBy(s => s.StudentId);
                    break;
                case "DegreeplanAbv_desc":
                    degreeplans = degreeplans.OrderBy(s => s.DegreePlanAbbrev);
                    break;
                case "DegreePlanName_desc":
                    degreeplans = degreeplans.OrderBy(s => s.DegreePlanName);
                    break;
                case "Degreeid_desc":
                    degreeplans = degreeplans.OrderByDescending(s => s.DegreeId);
                    break;
                case "Degreeid":
                    degreeplans = degreeplans.OrderBy(s => s.DegreeId);
                    break;
                default:
                    degreeplans = degreeplans.OrderBy(s => s.DegreePlanId);
                    break;
            }
            return View(await degreeplans.AsNoTracking().ToListAsync());
        }
    

        // GET: DegreePlans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var degreePlan = await _context.DegreePlans
                .Include(d => d.Degree)
                .Include(d => d.Student)
                .FirstOrDefaultAsync(m => m.DegreePlanId == id);
            if (degreePlan == null)
            {
                return NotFound();
            }

            return View(degreePlan);
        }

        // GET: DegreePlans/Create
        public IActionResult Create()
        {
            ViewData["DegreeId"] = new SelectList(_context.Degrees, "DegreeId", "DegreeAbbr");
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "Family");
            return View();
        }

        // POST: DegreePlans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DegreePlanId,DegreeId,StudentId,DegreePlanAbbrev,DegreePlanName, Done")] DegreePlan degreePlan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(degreePlan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DegreeId"] = new SelectList(_context.Degrees, "DegreeId", "DegreeAbbr", degreePlan.DegreeId);
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "Family", degreePlan.StudentId);
            return View(degreePlan);
        }

        // GET: DegreePlans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) { return NotFound(); }
            var studentDegreePlan = await _context.DegreePlans
                .Include(p => p.Degree).ThenInclude(pd => pd.Credits)
                .Include(p => p.Student)
                .Include(p => p.StudentTerms).ThenInclude(pt => pt.Slots)
                .SingleOrDefaultAsync(m => m.DegreePlanId == id);

            if (studentDegreePlan == null) { return NotFound(); }
            ViewData["DegreeId"] = new SelectList(_context.Degrees, "DegreeId", "DegreeAbrrev", studentDegreePlan.DegreeId);
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "First", studentDegreePlan.StudentId);
            return View(studentDegreePlan);
        }

        // POST: DegreePlans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DegreePlanId,DegreeId,StudentId,DegreePlanAbbrev,DegreePlanName")] DegreePlan degreePlan)
        {
            if (id != degreePlan.DegreePlanId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(degreePlan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DegreePlanExists(degreePlan.DegreePlanId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DegreeId"] = new SelectList(_context.Degrees, "DegreeId", "DegreeAbbr", degreePlan.DegreeId);
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "Family", degreePlan.StudentId);
            return View(degreePlan);
        }

        // GET: DegreePlans/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var degreePlan = await _context.DegreePlans
                .Include(d => d.Degree)
                .Include(d => d.Student)
                .FirstOrDefaultAsync(m => m.DegreePlanId == id);
            if (degreePlan == null)
            {
                return NotFound();
            }

            return View(degreePlan);
        }

        // POST: DegreePlans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var degreePlan = await _context.DegreePlans.FindAsync(id);
            _context.DegreePlans.Remove(degreePlan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DegreePlanExists(int id)
        {
            return _context.DegreePlans.Any(e => e.DegreePlanId == id);
        }
    }
}

StudentPlan/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentPlan.Data;
using StudentPlan.Models;

namespace StudentPlan.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["FamilyNameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Fname_desc" : "";
            ViewData["GivenNameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Gname_desc" : "";
            ViewData["SidSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Sid_desc" : "";
            ViewData["CatpawsidSortParm"] = sortOrder == "Catpawsids" ? "Catpawsid_desc" : "Catpawsid";
            ViewData["CurrentFilter"] = searchString;
            var students = from s in _context.Students
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.Family.Contains(searchString)
                                       || s.Given.Contains(searchString) || s.Snumber.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "Fname_desc":
                    students = students.OrderByDescending(s => s.Family);
                    break;
                case "Gname_desc":
                    students = students.OrderBy(s => s.Given);
                    break;
                case "Sid_desc":
                    students = students.OrderBy(s => s.Snumber);
                    break;
                case "Catpawsid_desc":
                    students = students.OrderByDescending(s => s.Number919);
                    break;
                default:
                    students = students.OrderBy(s => s.StudentId);
                    break;
            }
            return View(await students.AsNoTracking().ToListAsync());
        
    }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
              .Include(d => d.DegreePlans)
              .SingleOrDefaultAsync(m => m.StudentId == id);

            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StudentId,Family,Given,Snumber,Number919, Done")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StudentId,Family,Given,Snumber,Number919")] Student student)
        {
            if (id != student.StudentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.StudentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Students.FindAsync(id);
            _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return _context.Students.Any(e => e.StudentId == id);
        }
    }
}

StudentPlan/Views/Students/Create.cshtml
@model StudentPlan.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <input asp-for="StudentId" class="form-control" />
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Family" class="control-label"></label>
                <input asp-for="Family" class="form-control" />
                <span asp-validation-for="Family" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Given" class="control-label"></label>
                <input asp-for="Given" class="form-control" />
                <span asp-validation-for="Given" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Snumber" class="control-label"></label>
                <input asp-for="Snumber" class="form-control" />
                <span asp-validation-for="Snumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number919" class="control-label"></label>
                <input asp-for="Number919" class="form-control" />
                <span asp-validation-for="Number919" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudentPlan/Views/Students/Delete.cshtml
@model StudentPlan.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Family)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Family)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Given)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Given)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Snumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Snumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number919)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number919)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StudentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

StudentPlan/Views/Students/Details.cshtml
@model StudentPlan.Models.Student

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Family)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Family)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Given)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Given)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Snumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Snumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Number919)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Number919)
        </dd>
        <dd>
            <table class="table">
                <tr>
                    <th>DegreePlanId</th>
                    <th>DegreeId </th>
                    <th>StudentId</th>
                    <th> DegreePlanAbbrev </th>
                    <th>DegreePlanName</th>
                    <th> Done </th>
                    <th>StudentTerms</th>
                </tr>
                @foreach (var item in Model.DegreePlans.OrderBy(p => p.DegreePlanId))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.DegreePlanId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DegreeId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StudentId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DegreePlanAbbrev)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DegreePlanName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Done)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-controller="DegreePlans" asp-route-id="@item.DegreePlanId">Plan</a>
                        </td>
                    </tr>
                }
            </table>
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.StudentId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

StudentPlan/Views/Students/Edit.cshtml
@model StudentPlan.Models.Student

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StudentId" />
            <div class="form-group">
                <label asp-for="Family" class="control-label"></label>
                <input asp-for="Family" class="form-control" />
                <span asp-validation-for="Family" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Given" class="control-label"></label>
                <input asp-for="Given" class="form-control" />
                <span asp-validation-for="Given" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Snumber" class="control-label"></label>
                <input asp-for="Snumber" class="form-control" />
                <span asp-validation-for="Snumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number919" class="control-label"></label>
                <input asp-for="Number919" class="form-control" />
                <span asp-validation-for="Number919" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudentPlan/Views/Students/Index.cshtml
@model IEnumerable<StudentPlan.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by Family Name: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["FamilyNameSortParm"]">@Html.DisplayNameFor(model => model.Family)</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["GivenNameSortParm"]">@Html.DisplayNameFor(model => model.Given)</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["SIDSortParm"]">@Html.DisplayNameFor(model => model.Snumber)</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["CatpawsidSortParm"]">@Html.DisplayNameFor(model => model.Number919)</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Done)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Family)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Given)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Snumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number919)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Done)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.StudentId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.StudentId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.StudentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>